/**
 * Decorative PCB routing behind the top of every page.
 *
 * The geometry is generated by scripts/make-trace-field.mjs and pasted in
 * rather than fetched, so it costs no request and cannot 404 under a base path.
 * Regenerating with a different seed gives a different but equally plausible
 * board.
 *
 * WHY IT READS AS A BOARD AND NOT AS A TECH BACKGROUND
 *
 * Segments run at 0, 45 or 90 degrees and never anything else. Corners are
 * mitred, because a right angle is an acid trap in fabrication. Related signals
 * run as parallel bundles at constant pitch, which is most of what a dense board
 * looks like. Power is fat, signal is thin. Vias sit at the ends of runs rather
 * than scattered decoratively. Those rules are the whole difference between
 * texture and clip-art.
 *
 * It is static. An animated draw-in was considered and dropped: this sits behind
 * the first thing a recruiter reads, and motion there competes with the words for
 * no gain. Nothing here needs a prefers-reduced-motion branch as a result.
 *
 * aria-hidden and pointer-events-none, so it is invisible to assistive
 * technology and cannot intercept a click. The wrapper clips, which matters
 * because the artwork is wider than a phone and the suite asserts no horizontal
 * scroll at 375px.
 */
export default function TraceField() {
  return (
    <div
      aria-hidden="true"
      className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[34rem] overflow-hidden"
    >
      <svg
        viewBox="0 0 1600 620"
        preserveAspectRatio="xMidYMin slice"
        className="h-full w-full text-accent"
        style={{
          // Fades downward so the routing never competes with body text. A mask
          // rather than an overlay gradient, so it works against whatever ground
          // the active theme supplies instead of needing a matching colour.
          maskImage: 'linear-gradient(to bottom, black 0%, black 20%, transparent 75%)',
          WebkitMaskImage:
            'linear-gradient(to bottom, black 0%, black 20%, transparent 75%)',
        }}
      >
        <g
          fill="none"
          stroke="currentColor"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="opacity-[0.14] dark:opacity-[0.20]"
        >
          <g strokeWidth={2}>
          <path d="M 1113.2 535.8 L 1295.6 353.4 L 1302.7 336.3 L 1302.7 278.3 L 1295.6 261.2 L 1127.4 93.0" />
          <path d="M 1119.6 542.2 L 1251.8 409.9 L 1258.9 392.9 L 1258.9 153.9 L 1265.9 136.8 L 1310.5 92.3" />
          <path d="M 525.0 210.2 L 625.0 210.2 L 642.0 217.3 L 713.5 288.7 L 730.5 295.8 L 924.5 295.8 L 941.6 302.8 L 1126.8 488.1" />
          <path d="M 525.0 219.2 L 703.0 219.2 L 720.0 226.3 L 855.8 362.0 L 872.9 369.1 L 1026.9 369.1 L 1043.9 362.0 L 1223.5 182.5" />
          <path d="M 525.0 228.2 L 654.0 228.2 L 671.0 235.3 L 851.3 415.6 L 868.4 422.6 L 1052.4 422.6 L 1069.5 429.7 L 1143.7 503.9" />
          <path d="M 525.0 237.2 L 616.0 237.2 L 633.0 244.3 L 801.3 412.5 L 818.4 419.6 L 999.4 419.6 L 1016.5 412.5 L 1074.4 354.6" />
          <path d="M 319.1 441.8 L 485.2 275.6 L 502.3 268.6 L 760.3 268.6 L 777.4 261.5 L 872.8 166.0" />
          <path d="M 325.4 448.2 L 471.1 302.5 L 478.2 285.4 L 478.2 94.4 L 485.2 77.4 L 546.7 15.8" />
          <path d="M 1415.3 441.9 L 1545.3 441.9 L 1562.4 434.8 L 1645.8 351.4 L 1662.9 344.3 L 1812.9 344.3" />
          <path d="M 1415.3 450.9 L 1621.3 450.9 L 1638.4 443.8 L 1670.9 411.3 L 1688.0 404.2 L 1801.0 404.2" />
          <path d="M 864.3 30.9 L 864.3 86.9 L 871.4 104.0 L 1041.1 273.6 L 1058.1 280.7 L 1285.1 280.7 L 1302.2 273.6 L 1406.1 169.7" />
          <path d="M 855.3 30.9 L 855.3 201.9 L 862.4 219.0 L 951.5 308.0 L 958.5 325.1 L 958.5 562.1 L 965.6 579.2 L 1138.8 752.4" />
          <path d="M 675.8 87.2 L 675.8 220.2 L 682.9 237.3 L 723.9 278.3 L 741.0 285.4 L 901.0 285.4 L 918.0 278.3 L 1020.6 175.8" />
          <path d="M 666.8 87.2 L 666.8 343.2 L 659.7 360.3 L 538.1 481.9 L 531.1 499.0 L 531.1 567.0 L 538.1 584.0 L 656.2 702.1" />
          <path d="M 657.8 87.2 L 657.8 324.2 L 664.9 341.3 L 726.4 402.8 L 733.5 419.9 L 733.5 641.9 L 726.4 658.9 L 642.3 743.1" />
          <path d="M 648.8 87.2 L 648.8 207.2 L 655.9 224.3 L 686.3 254.7 L 703.4 261.8 L 775.4 261.8 L 792.4 254.7 L 937.4 109.8" />
          <path d="M 380.0 103.3 L 380.0 194.3 L 372.9 211.4 L 278.2 306.1 L 271.1 323.2 L 271.1 557.2 L 264.0 574.3 L 86.6 751.7" />
          <path d="M 371.0 103.3 L 371.0 293.3 L 363.9 310.4 L 198.5 475.8 L 191.4 492.9 L 191.4 617.9 L 184.3 635.0 L 47.9 771.4" />
          <path d="M 362.0 103.3 L 362.0 177.3 L 369.1 194.4 L 499.9 325.2 L 506.9 342.3 L 506.9 448.3 L 514.0 465.3 L 648.3 599.7" />
          <path d="M 353.0 103.3 L 353.0 305.3 L 345.9 322.4 L 273.1 395.2 L 256.0 402.3 L 84.0 402.3 L 67.0 395.2 L -46.9 281.4" />
          <path d="M 925.4 127.4 L 1107.8 309.8 L 1114.9 326.9 L 1114.9 545.9 L 1107.8 562.9 L 924.0 746.8" />
          <path d="M 1213.3 613.0 L 1332.1 731.8" />
          <path d="M 43.5 272.2 L 107.8 336.6 L 114.9 353.7 L 114.9 473.7" />
          <path d="M 1585.2 481.1 L 1737.2 481.1" />
          <path d="M 901.8 257.8 L 1114.8 257.8 L 1131.9 264.9 L 1195.5 328.5 L 1202.6 345.6 L 1202.6 568.6 L 1195.5 585.6 L 1063.3 717.8" />
          <path d="M 758.0 349.6 L 758.0 617.6 L 750.9 634.6 L 694.4 691.2" />
          <path d="M 1193.9 385.4 L 1377.7 569.3 L 1384.8 586.3 L 1384.8 651.3" />
          <path d="M 1379.5 443.4 L 1551.3 271.5 L 1568.4 264.5 L 1748.4 264.5" />
          <path d="M 146.1 128.8 L 322.1 128.8 L 339.2 135.9 L 405.7 202.4 L 412.7 219.4 L 412.7 435.4 L 419.8 452.5 L 577.5 610.2" />
          <path d="M 904.9 89.0 L 973.5 20.4 L 990.5 13.3 L 1122.5 13.3 L 1139.6 20.4 L 1312.8 193.6" />
          <path d="M 1356.1 337.1 L 1498.2 195.0 L 1515.3 187.9 L 1591.3 187.9 L 1608.3 195.0 L 1766.7 353.3" />
          <path d="M 1231.0 480.2 L 1354.1 603.3 L 1361.1 620.3 L 1361.1 674.3" />
          <path d="M 758.9 303.9 L 867.8 412.8 L 874.9 429.9 L 874.9 649.9" />
          <path d="M 863.9 192.0 L 979.2 307.2 L 986.3 324.3 L 986.3 454.3" />
          </g>
          <g strokeWidth={5}>
          <path d="M 1080.8 380.9 L 1232.2 532.2 L 1239.2 549.3 L 1239.2 761.3" />
          <path d="M 23.2 246.5 L 171.7 394.9 L 178.7 412.0 L 178.7 645.0" />
          <path d="M 1512.8 4.4 L 1601.2 92.8 L 1608.3 109.8 L 1608.3 333.8" />
          </g>
          <g strokeWidth={2.5}>
          <circle cx="1126.8" cy="488.1" r="4" />
          <circle cx="1143.7" cy="503.9" r="4" />
          <circle cx="546.7" cy="15.8" r="4" />
          <circle cx="937.4" cy="109.8" r="4" />
          <circle cx="648.3" cy="599.7" r="4" />
          <circle cx="986.3" cy="454.3" r="4" />
          </g>
        </g>
      </svg>
    </div>
  )
}
